services:
  web:
    build: .
    platform: linux/amd64
    env_file:
      - .env
    ports:
      - '3000:3000'
    environment:
      - 'DATABASE_PASSWORD=${MYAPP_DATABASE_PASSWORD}'
    volumes:
      - .:/rails-docker
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: postgres:12
    platform: linux/amd64
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    env_file:
      - .env
    environment:
      - 'POSTGRES_USER=${MYAPP_DATABASE_PASSWORD}'
      - 'POSTGRES_PASSWORD=${MYAPP_DATABASE_PASSWORD}'
volumes:
  db-data: