volumes:
  db-data:

services:
  web:
    build: .
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
               bundle exec rails server -b '0.0.0.0'"
    env_file:
      - .env
    ports:
      - '3000:3000'
    environment:
      - 'DATABASE_PASSWORD=${MYAPP_DATABASE_PASSWORD}'
    volumes:
      - .:/myapp
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:12
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    env_file:
      - .env
    environment:
      - 'POSTGRES_USER=${MYAPP_DATABASE_PASSWORD}'
      - 'POSTGRES_PASSWORD=${MYAPP_DATABASE_PASSWORD}'